language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-hystory: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: gh-pages
  commit_message: "Manejador de paginas agregado"
  on: 
    branch: master